# Generated by Django 5.2.3 on 2025-10-26 13:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dbgsrmvgi/image/upload/v1761485514/default_k1ou2x.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
