# Generated by Django 5.2.3 on 2025-06-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
    ]
