# Generated by Django 5.2.3 on 2025-10-26 13:23

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='default_event_img.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
