# Generated by Django 5.2.3 on 2025-07-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_participants_delete_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, default='default_event_img.jpg', null=True, upload_to='tasks_asset'),
        ),
    ]
