# Generated by Django 5.2.3 on 2025-10-26 13:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='https://res.cloudinary.com/dbgsrmvgi/image/upload/v1761485481/065b9bff-better-meetings-500x400-1_dr1rfj.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
