# Generated by Django 5.2.3 on 2025-07-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, default='default_event_img.jpg', null=True, upload_to='event_images'),
        ),
    ]
