# Generated by Django 5.2.3 on 2025-07-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, default='default_event_img.png', null=True, upload_to='event_images'),
        ),
    ]
